//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 02:03:45 PM CET 
//


package uzuzjmd.competence.shared.epos;

import uzuzjmd.competence.shared.epos.DESCRIPTORSETType;
import uzuzjmd.competence.shared.epos.DESCRIPTORType;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uzuzjmd.competence.datasource.epos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DESCRIPTORSET_QNAME = new QName("", "DESCRIPTORSET");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uzuzjmd.competence.datasource.epos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DESCRIPTORSETType }
     * 
     */
    public DESCRIPTORSETType createDESCRIPTORSETType() {
        return new DESCRIPTORSETType();
    }

    /**
     * Create an instance of {@link DESCRIPTORType }
     * 
     */
    public DESCRIPTORType createDESCRIPTORType() {
        return new DESCRIPTORType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DESCRIPTORSETType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DESCRIPTORSET")
    public JAXBElement<DESCRIPTORSETType> createDESCRIPTORSET(DESCRIPTORSETType value) {
        return new JAXBElement<DESCRIPTORSETType>(_DESCRIPTORSET_QNAME, DESCRIPTORSETType.class, null, value);
    }

}
