/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CommentData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CommentData'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.CompetenceLinksView = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.CommentData);
  }
}(this, function(ApiClient, CommentData) {
  'use strict';




  /**
   * The CompetenceLinksView model module.
   * @module model/CompetenceLinksView
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CompetenceLinksView</code>.
   * @alias module:model/CompetenceLinksView
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>CompetenceLinksView</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompetenceLinksView} obj Optional instance to populate.
   * @return {module:model/CompetenceLinksView} The populated <code>CompetenceLinksView</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('abstractLinkId')) {
        obj['abstractLinkId'] = ApiClient.convertToType(data['abstractLinkId'], 'String');
      }
      if (data.hasOwnProperty('evidenceTitel')) {
        obj['evidenceTitel'] = ApiClient.convertToType(data['evidenceTitel'], 'String');
      }
      if (data.hasOwnProperty('evidenceUrl')) {
        obj['evidenceUrl'] = ApiClient.convertToType(data['evidenceUrl'], 'String');
      }
      if (data.hasOwnProperty('comments')) {
        obj['comments'] = ApiClient.convertToType(data['comments'], [CommentData]);
      }
      if (data.hasOwnProperty('validated')) {
        obj['validated'] = ApiClient.convertToType(data['validated'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} abstractLinkId
   */
  exports.prototype['abstractLinkId'] = undefined;
  /**
   * @member {String} evidenceTitel
   */
  exports.prototype['evidenceTitel'] = undefined;
  /**
   * @member {String} evidenceUrl
   */
  exports.prototype['evidenceUrl'] = undefined;
  /**
   * @member {Array.<module:model/CommentData>} comments
   */
  exports.prototype['comments'] = undefined;
  /**
   * @member {Boolean} validated
   * @default false
   */
  exports.prototype['validated'] = false;



  return exports;
}));


