/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.CompetenceData = factory(root.SwaggerJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CompetenceData model module.
   * @module model/CompetenceData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CompetenceData</code>.
   * @alias module:model/CompetenceData
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>CompetenceData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompetenceData} obj Optional instance to populate.
   * @return {module:model/CompetenceData} The populated <code>CompetenceData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('operator')) {
        obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
      }
      if (data.hasOwnProperty('catchwords')) {
        obj['catchwords'] = ApiClient.convertToType(data['catchwords'], ['String']);
      }
      if (data.hasOwnProperty('superCompetences')) {
        obj['superCompetences'] = ApiClient.convertToType(data['superCompetences'], ['String']);
      }
      if (data.hasOwnProperty('subCompetences')) {
        obj['subCompetences'] = ApiClient.convertToType(data['subCompetences'], ['String']);
      }
      if (data.hasOwnProperty('learningProjectName')) {
        obj['learningProjectName'] = ApiClient.convertToType(data['learningProjectName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} operator
   */
  exports.prototype['operator'] = undefined;
  /**
   * @member {Array.<String>} catchwords
   */
  exports.prototype['catchwords'] = undefined;
  /**
   * @member {Array.<String>} superCompetences
   */
  exports.prototype['superCompetences'] = undefined;
  /**
   * @member {Array.<String>} subCompetences
   */
  exports.prototype['subCompetences'] = undefined;
  /**
   * @member {String} learningProjectName
   */
  exports.prototype['learningProjectName'] = undefined;



  return exports;
}));


