/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Evidence'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Evidence'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.EvidenceData = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.Evidence);
  }
}(this, function(ApiClient, Evidence) {
  'use strict';




  /**
   * The EvidenceData model module.
   * @module model/EvidenceData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EvidenceData</code>.
   * @alias module:model/EvidenceData
   * @class
   * @param creator {String} the id of the creator
   * @param competences {Array.<String>} the list of competences proven
   * @param evidence {module:model/Evidence} the activity (as in urls) that show the prove
   */
  var exports = function(creator, competences, evidence) {
    var _this = this;


    _this['creator'] = creator;
    _this['competences'] = competences;
    _this['evidence'] = evidence;
  };

  /**
   * Constructs a <code>EvidenceData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EvidenceData} obj Optional instance to populate.
   * @return {module:model/EvidenceData} The populated <code>EvidenceData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('courseId')) {
        obj['courseId'] = ApiClient.convertToType(data['courseId'], 'String');
      }
      if (data.hasOwnProperty('creator')) {
        obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
      }
      if (data.hasOwnProperty('competences')) {
        obj['competences'] = ApiClient.convertToType(data['competences'], ['String']);
      }
      if (data.hasOwnProperty('evidence')) {
        obj['evidence'] = Evidence.constructFromObject(data['evidence']);
      }
    }
    return obj;
  }

  /**
   * @member {String} courseId
   */
  exports.prototype['courseId'] = undefined;
  /**
   * the id of the creator
   * @member {String} creator
   */
  exports.prototype['creator'] = undefined;
  /**
   * the list of competences proven
   * @member {Array.<String>} competences
   */
  exports.prototype['competences'] = undefined;
  /**
   * the activity (as in urls) that show the prove
   * @member {module:model/Evidence} evidence
   */
  exports.prototype['evidence'] = undefined;



  return exports;
}));


