/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.GraphTriple = factory(root.SwaggerJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GraphTriple model module.
   * @module model/GraphTriple
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GraphTriple</code>.
   * @alias module:model/GraphTriple
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>GraphTriple</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GraphTriple} obj Optional instance to populate.
   * @return {module:model/GraphTriple} The populated <code>GraphTriple</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('node1id')) {
        obj['node1id'] = ApiClient.convertToType(data['node1id'], 'Integer');
      }
      if (data.hasOwnProperty('node2id')) {
        obj['node2id'] = ApiClient.convertToType(data['node2id'], 'Integer');
      }
      if (data.hasOwnProperty('fromNode')) {
        obj['fromNode'] = ApiClient.convertToType(data['fromNode'], 'String');
      }
      if (data.hasOwnProperty('toNode')) {
        obj['toNode'] = ApiClient.convertToType(data['toNode'], 'String');
      }
      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('directed')) {
        obj['directed'] = ApiClient.convertToType(data['directed'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} node1id
   */
  exports.prototype['node1id'] = undefined;
  /**
   * @member {Integer} node2id
   */
  exports.prototype['node2id'] = undefined;
  /**
   * @member {String} fromNode
   */
  exports.prototype['fromNode'] = undefined;
  /**
   * @member {String} toNode
   */
  exports.prototype['toNode'] = undefined;
  /**
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * @member {Boolean} directed
   * @default false
   */
  exports.prototype['directed'] = false;



  return exports;
}));


