/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Graph', 'model/GraphNode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Graph'), require('./GraphNode'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.LearningTemplateResultSet = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.Graph, root.SwaggerJsClient.GraphNode);
  }
}(this, function(ApiClient, Graph, GraphNode) {
  'use strict';




  /**
   * The LearningTemplateResultSet model module.
   * @module model/LearningTemplateResultSet
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>LearningTemplateResultSet</code>.
   * @alias module:model/LearningTemplateResultSet
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>LearningTemplateResultSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LearningTemplateResultSet} obj Optional instance to populate.
   * @return {module:model/LearningTemplateResultSet} The populated <code>LearningTemplateResultSet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('root')) {
        obj['root'] = GraphNode.constructFromObject(data['root']);
      }
      if (data.hasOwnProperty('resultGraph')) {
        obj['resultGraph'] = Graph.constructFromObject(data['resultGraph']);
      }
      if (data.hasOwnProperty('catchwordMap')) {
        obj['catchwordMap'] = ApiClient.convertToType(data['catchwordMap'], {'String': ['String']});
      }
      if (data.hasOwnProperty('nameOfTheLearningTemplate')) {
        obj['nameOfTheLearningTemplate'] = ApiClient.convertToType(data['nameOfTheLearningTemplate'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/GraphNode} root
   */
  exports.prototype['root'] = undefined;
  /**
   * @member {module:model/Graph} resultGraph
   */
  exports.prototype['resultGraph'] = undefined;
  /**
   * @member {Object.<String, Array.<String>>} catchwordMap
   */
  exports.prototype['catchwordMap'] = undefined;
  /**
   * @member {String} nameOfTheLearningTemplate
   */
  exports.prototype['nameOfTheLearningTemplate'] = undefined;



  return exports;
}));


