/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.LearningTemplateData = factory(root.SwaggerJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LearningTemplateData model module.
   * @module model/LearningTemplateData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>LearningTemplateData</code>.
   * @alias module:model/LearningTemplateData
   * @class
   * @param userName {String} the user id (email)
   * @param groupId {String} course context (in liferay group id)
   */
  var exports = function(userName, groupId) {
    var _this = this;

    _this['userName'] = userName;
    _this['groupId'] = groupId;


  };

  /**
   * Constructs a <code>LearningTemplateData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LearningTemplateData} obj Optional instance to populate.
   * @return {module:model/LearningTemplateData} The populated <code>LearningTemplateData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('userName')) {
        obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
      }
      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'String');
      }
      if (data.hasOwnProperty('selectedTemplate')) {
        obj['selectedTemplate'] = ApiClient.convertToType(data['selectedTemplate'], 'String');
      }
      if (data.hasOwnProperty('competences')) {
        obj['competences'] = ApiClient.convertToType(data['competences'], ['String']);
      }
    }
    return obj;
  }

  /**
   * the user id (email)
   * @member {String} userName
   */
  exports.prototype['userName'] = undefined;
  /**
   * course context (in liferay group id)
   * @member {String} groupId
   */
  exports.prototype['groupId'] = undefined;
  /**
   * the name of the template
   * @member {String} selectedTemplate
   */
  exports.prototype['selectedTemplate'] = undefined;
  /**
   * the competences associated with this template
   * @member {Array.<String>} competences
   */
  exports.prototype['competences'] = undefined;



  return exports;
}));


