/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SuggestedCompetenceColumn'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SuggestedCompetenceColumn'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.SuggestedCompetenceRow = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.SuggestedCompetenceColumn);
  }
}(this, function(ApiClient, SuggestedCompetenceColumn) {
  'use strict';




  /**
   * The SuggestedCompetenceRow model module.
   * @module model/SuggestedCompetenceRow
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SuggestedCompetenceRow</code>.
   * @alias module:model/SuggestedCompetenceRow
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SuggestedCompetenceRow</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuggestedCompetenceRow} obj Optional instance to populate.
   * @return {module:model/SuggestedCompetenceRow} The populated <code>SuggestedCompetenceRow</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('suggestedCompetenceColumns')) {
        obj['suggestedCompetenceColumns'] = ApiClient.convertToType(data['suggestedCompetenceColumns'], [SuggestedCompetenceColumn]);
      }
      if (data.hasOwnProperty('suggestedCompetenceRowHeader')) {
        obj['suggestedCompetenceRowHeader'] = ApiClient.convertToType(data['suggestedCompetenceRowHeader'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/SuggestedCompetenceColumn>} suggestedCompetenceColumns
   */
  exports.prototype['suggestedCompetenceColumns'] = undefined;
  /**
   * @member {String} suggestedCompetenceRowHeader
   */
  exports.prototype['suggestedCompetenceRowHeader'] = undefined;



  return exports;
}));


