/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.SyncDataSet = factory(root.SwaggerJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SyncDataSet model module.
   * @module model/SyncDataSet
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SyncDataSet</code>.
   * @alias module:model/SyncDataSet
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>SyncDataSet</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SyncDataSet} obj Optional instance to populate.
   * @return {module:model/SyncDataSet} The populated <code>SyncDataSet</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('userName')) {
        obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('syncBadges')) {
        obj['syncBadges'] = ApiClient.convertToType(data['syncBadges'], 'Boolean');
      }
      if (data.hasOwnProperty('syncCourses')) {
        obj['syncCourses'] = ApiClient.convertToType(data['syncCourses'], 'Boolean');
      }
      if (data.hasOwnProperty('syncActivities')) {
        obj['syncActivities'] = ApiClient.convertToType(data['syncActivities'], 'Boolean');
      }
      if (data.hasOwnProperty('syncUsers')) {
        obj['syncUsers'] = ApiClient.convertToType(data['syncUsers'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} userName
   */
  exports.prototype['userName'] = undefined;
  /**
   * @member {String} password
   */
  exports.prototype['password'] = undefined;
  /**
   * @member {Boolean} syncBadges
   * @default false
   */
  exports.prototype['syncBadges'] = false;
  /**
   * @member {Boolean} syncCourses
   * @default false
   */
  exports.prototype['syncCourses'] = false;
  /**
   * @member {Boolean} syncActivities
   * @default false
   */
  exports.prototype['syncActivities'] = false;
  /**
   * @member {Boolean} syncUsers
   * @default false
   */
  exports.prototype['syncUsers'] = false;



  return exports;
}));


