/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.UserData = factory(root.SwaggerJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UserData model module.
   * @module model/UserData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserData</code>.
   * @alias module:model/UserData
   * @class
   * @param userId {String} the id (email) of the learner the who has evidenced the competence
   * @param role {String} role can either be 'teacher' or 'student'
   */
  var exports = function(userId, role) {
    var _this = this;

    _this['userId'] = userId;

    _this['role'] = role;


  };

  /**
   * Constructs a <code>UserData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserData} obj Optional instance to populate.
   * @return {module:model/UserData} The populated <code>UserData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
      if (data.hasOwnProperty('courseContext')) {
        obj['courseContext'] = ApiClient.convertToType(data['courseContext'], 'String');
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
      if (data.hasOwnProperty('printableName')) {
        obj['printableName'] = ApiClient.convertToType(data['printableName'], 'String');
      }
      if (data.hasOwnProperty('lmsSystems')) {
        obj['lmsSystems'] = ApiClient.convertToType(data['lmsSystems'], 'String');
      }
    }
    return obj;
  }

  /**
   * the id (email) of the learner the who has evidenced the competence
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * @member {String} courseContext
   */
  exports.prototype['courseContext'] = undefined;
  /**
   * role can either be 'teacher' or 'student'
   * @member {String} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {String} printableName
   */
  exports.prototype['printableName'] = undefined;
  /**
   * @member {String} lmsSystems
   */
  exports.prototype['lmsSystems'] = undefined;



  return exports;
}));


